# Generated by Django 5.2.6 on 2025-10-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Как тебя зовут?')),
                ('date_of_birth', models.DateField(verbose_name='Укажи дату рождения?')),
                ('application', models.CharField(verbose_name='На кого ты учишься?')),
                ('instagram', models.URLField(verbose_name='Укажи ссылку на инстрам')),
                ('subject', models.CharField(choices=[('Программирование', 'Программирование'), ('Математика', 'Математика'), ('Химия', 'Химия'), ('Биология', 'Биология')], max_length=100, verbose_name='Какой твой любимый предмет')),
                ('photo', models.URLField(verbose_name='Укажите ссылку на фотку')),
                ('education', models.FileField(blank=True, upload_to='students/', verbose_name='загрузите ваш диплом')),
            ],
        ),
    ]
