# Generated by Django 5.2.6 on 2025-09-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='films/', verbose_name='загрузите картинку фильма')),
                ('title', models.CharField(max_length=100, verbose_name='напишите название фильма')),
                ('description', models.TextField(verbose_name='укажите описание к фильму')),
                ('genre', models.CharField(choices=[('Ужасы', 'Ужасы'), ('Фантастика', 'Фантастика'), ('Боевики', 'Боевики')], default='Фантастика', max_length=100)),
                ('director', models.CharField(blank=True, max_length=100, verbose_name='укажите режисера')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='укажите кол-во серий')),
                ('trailer', models.URLField(verbose_name='укажите ссылку с youtube')),
            ],
        ),
    ]
