# Generated by Django 5.2.6 on 2025-10-03 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShow', '0002_alter_films_options_films_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='поставьте оценку от 1 до 5')),
                ('review_text', models.TextField(default='Прикольный фильм')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tvShow.films')),
            ],
        ),
    ]
