# Generated by Django 5.2.6 on 2025-10-03 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvShow', '0003_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Антон', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Автовладелец',
                'verbose_name_plural': 'Автовладельцы',
            },
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_car', models.CharField(default='Mercedes B-class', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='tvShow.person')),
            ],
        ),
    ]
