# Generated by Django 5.2.6 on 2025-10-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvShow', '0004_person_alter_reviews_options_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'машину', 'verbose_name_plural': 'машины'},
        ),
    ]
